### ISSUE TITLE
Why you are not using create method of default Model class in EloquentRepository.php ?

### ISSUE THREAD

**Issue by bedus-creation** [sbine/bdgt#10]
`    public function create(array $data)
    {
        if (empty($data)) {
            return null;
        }

        $instance = $this->instance();

        foreach ($data as $key => $value) {
            $instance->setAttribute($key, $value);
        }

        if ($instance->save()) {
            return $instance;
        }
        return null;
    }`

**Comment by ryanwohara** [comment]
Can you open a PR for this?
