### ISSUE TITLE
Improve Reports on mobile

### ISSUE THREAD

**Issue by sbine** [sbine/bdgt#13]
Reports look pretty wonky on mobile screens; see if there's something that can be done in either ChartJS or Vue to improve the experience.

The Vue components for reports can be found at [resources/js/components/reports/](https://github.com/sbine/bdgt/blob/1522d3f861d7135c93026e6b807d8b738d40b966/resources/js/components/reports/). The frontend assets will [need to be recompiled](https://github.com/sbine/bdgt/tree/1522d3f861d7135c93026e6b807d8b738d40b966#building-the-frontend-assets) after components are changed.

![image](https://user-images.githubusercontent.com/1902973/68091618-bfbc7980-fe36-11e9-8bf5-bc3862f7a3e1.png)

**Comment by juliano-nunes** [comment]
Hey @sbine, can you assign this one to me? I think I have found a way to optmize this! :)
 
![image](https://user-images.githubusercontent.com/22858307/95033756-a995e980-0695-11eb-8615-a79350f5c78b.png)

**Comment by sbine** [comment]
Fixed in #45
