### ISSUE TITLE
Transaction sort by amount doesn't take inflow/outflow into account

### ISSUE THREAD

**Issue by sbine** [sbine/bdgt#26]
When sorting by transaction amount, sign (positive/negative, which is represented in bdgt by the `inflow` boolean on each transaction) should be taken into account. Currently negative outflow numbers are mixed in with positive inflow numbers–see the screenshot below, where the correct order would be `$1,000`, `$100`, `-$59.99`, `-$90.51`, `-$155.22`, `-$200`.

![image](https://user-images.githubusercontent.com/1902973/95004426-28145d80-05a8-11eb-9e9e-229fb79a649c.png)

- Sorting is done in [TransactionsTable.vue](https://github.com/sbine/bdgt/blob/master/resources/js/components/TransactionsTable.vue) (by [vue-tables-2](https://github.com/matfish2/vue-tables-2)).
- To work on this task you'll need to know how to [build the frontend assets](https://github.com/sbine/bdgt#building-the-frontend-assets).

**Comment by vclayton** [comment]
I'd like to take a crack at this.
