### ISSUE TITLE
Select nice-looking static colors for reports

### ISSUE THREAD

**Issue by sbine** [sbine/bdgt#29]
bdgt's reports are currently generated using random colors that change every time you refresh the page. It was a fun gimmick, but long-term it would be preferable to have some complementary colors that look good and aren't constantly changing.

This issue covers:
- Selecting a new set of colors that look nice together but are easy to differentiate
- Updating both reports so categories generally keep appearing in the same color through page refreshes (but it's OK if they change when the list of categories changes)

As a starting point, I like the colors shown in the bar chart in the README (screenshot below)–but I'm not a designer, so [here's a designer's advice](https://blog.datawrapper.de/beautifulcolors/) on selecting colors for data visualization.

![screenshot: reports](https://sarabine.com/bdgt-reports.png)

- Pie chart is in [SpendingByCategory.vue](https://github.com/sbine/bdgt/blob/master/resources/js/components/reports/SpendingByCategory.vue#L19)
- Bar chart is in [SpendingOverTime.vue](https://github.com/sbine/bdgt/blob/master/resources/js/components/reports/SpendingOverTime.vue#L20)
- To work on this task you'll need to know how to [build the frontend assets](https://github.com/sbine/bdgt#building-the-frontend-assets)

Please include a screenshot in your PR :)

**Comment by ccmetz** [comment]
Hey @sbine, I'd like to work on this one!

**Comment by ziad696** [comment]
hi @sbine , maybe i can try...

**Comment by ActuallyConnor** [comment]
Hey @sbine I have made a PR for this issue that you can checkout here https://github.com/sbine/bdgt/pull/42

**Comment by sbine** [comment]
Fixed in #40 and #42
