### ISSUE TITLE
When adding a transaction, default the date to today

### ISSUE THREAD

**Issue by sbine** [sbine/bdgt#37]
When creating a new transaction (not when editing), the 'Date' field should default to today's date. Currently it has no default value.

![image](https://user-images.githubusercontent.com/1902973/95022830-b9caac00-0636-11eb-9645-3ff58f631a1d.png)

- The date field is in [TransactionForm.vue](https://github.com/sbine/bdgt/blob/master/resources/js/components/forms/TransactionForm.vue#L17)
- The datepicker component is in [InputDatepicker.vue](https://github.com/sbine/bdgt/blob/master/resources/js/components/interface/InputDatepicker.vue#L39)
- To work on this task you'll need to know how to [build the frontend assets](https://github.com/sbine/bdgt/blob/master/README.md#building-the-frontend-assets)

**Comment by cdterry87** [comment]
I wouldn't mind giving this one a shot, if that's okay :)

**Comment by cdterry87** [comment]
@sbine It looks like this may be a little more complicated than originally anticipated.

The "Add a Transaction" modal form actually appears to be located in `resources/views/transaction/_form.blade.php` while the "Edit transaction" version is in the `TransactionForm.vue` file.  I noticed this after I discovered that the `creating` computed property in `TransactionForm.vue` is never actually getting set to true, even when clicking "Add Transaction" on the dashboard.

The "easy" solution in the `_form.blade.php` file would be to change the `<input-datepicker>` component to `<input-datepicker name="date" value="{{ date('m/d/Y') }}" required></input-datepicker>` which will default the date to the current date anytime the "Add a Transaction" modal is opened.  I tested it this way and it does seem to work, but I'm not sure if this is the best solution.  It seems like the intent was to use the TransactionForm vue component for all the transaction forms, but I couldn't find a good way to refactor it myself. 😅

**Comment by sbine** [comment]
@cdterry87 oops, I must not have finished one of the refactors on those forms. I'm OK with the Blade solution in `_form.blade.php` for now, thanks for digging into it!

**Comment by cdterry87** [comment]
@sbine  No problem! This is a really cool project and was fun to dig through the code. I'd be interested in working on any further issues if any others come up in the future. Thanks for letting me contribute!

**Comment by sbine** [comment]
Closed in #44
