### ISSUE TITLE
Add support for OFX file imports

### ISSUE THREAD

**Issue by sbine** [sbine/bdgt#50]
Supporting [OFX](https://en.wikipedia.org/wiki/Open_Financial_Exchange) file imports would be a great enhancement to bdgt. At one point I pulled in the library [asgrim/ofxparser](https://github.com/asgrim/ofxparser) which is still in the repo (but now unmaintained).

If anyone would like to attempt this, I think an Artisan command that accepts two arguments would be the simplest start: something like `php artisan import [user id or email] [path to OFX file]`

**Comment by murilopereirame** [comment]
Hi! Could u explain a little more how u would like it fit into the system? 

**Like:** 
- The user needs to have the same account in the system as into the OFX?
- The transactions will receive an tag marking as OFX Imported?

Thx, u repo is amazing.

**Comment by sbine** [comment]
@murilopereirame good questions, I think I'm okay with either option for the first attempt: either transactions are only imported for existing accounts, or accounts that don't exist can be created during an import.

There isn't a tagging mechanism for transactions right now, but there should be! I would accept a PR for it :) but for now I don't think we need to mark the imported transactions in any special way.

**Comment by murilopereirame** [comment]
Alright! I will work on OFX, could u assign it to me? Thx.

**Comment by SaifurRahmanMohsin** [comment]
Hey it's been 6 days, can I handle this instead? Trying for hacktoberfest as well.
