### ISSUE TITLE
Add support for exporting transactions

### ISSUE THREAD

**Issue by sbine** [sbine/bdgt#51]
It's important that users be able to export/own their bdgt data.

If anyone would like to attempt this, I think an Artisan command that generates a CSV of transactions would be the simplest start: something like `php artisan export [user id or email]` (though if you'd like to build the UI, you're certainly welcome to!)

**Comment by jamesriady** [comment]
I try to do this PR [#56](https://github.com/sbine/bdgt/pull/56)

**Comment by sbine** [comment]
Closed by #56
