### ISSUE TITLE
Add support for date filtering in reports

### ISSUE THREAD

**Issue by sbine** [sbine/bdgt#61]
bdgt's [reports](https://github.com/sbine/bdgt/tree/master/resources/js/components/reports) could be much improved by adding support for custom date filtering. The backend was [written with date filtering in mind](https://github.com/sbine/bdgt/blob/master/app/Http/Controllers/ReportController.php#L30) (`{ startDate: '', endDate: '' }`), I've just never hooked it up to the UI.

Ideally these would use V-Calendar's [date range](https://vcalendar.io/datepicker.html#date-range) picker that's already bundled into the app; for now just sticking it in the upper right corner of each report is fine.

![image](https://user-images.githubusercontent.com/1902973/95693111-dee78d80-0be7-11eb-98da-44e8ad99df1a.png)

- To work on this you'll need to know how to [build the frontend assets](https://github.com/sbine/bdgt/blob/master/README.md#building-the-frontend-assets)
- It would be awesome if the backend enforced a maximum filter range of 1 year, but this isn't required

**Comment by g1dra** [comment]
Hi. Can you assign me I can help with this issue?

**Comment by sbine** [comment]
Awesome @g1dra! I don't do assigned issues (sometimes I get multiple good PRs doing different parts of the same one) but it's yours to work on. 🙂

**Comment by g1dra** [comment]
> * It would be awesome if the backend enforced a maximum filter range of 1 year, but this isn't require

Pls explain this more. One year from before current time?

**Comment by sbine** [comment]
I'm thinking the backend would take whatever `startDate` the frontend provided and, if `endDate` was more than 1 year later than `startDate`, just reset `endDate` to `startDate + 1 year`. Does that make sense?

**Comment by g1dra** [comment]
Well depends how do you plan to use the page. I can validate it like you ask. What is the reason to limit it like that?
