### ISSUE TITLE
Datepicker in transaction modal should close when losing focus

### ISSUE THREAD

**Issue by sbine** [sbine/bdgt#65]
The [v-calendar](https://github.com/nathanreyes/v-calendar) datepicker used in the transaction modal remains on the screen until a date is clicked on, or the input field is clicked on again.

It should disappear if:
1. the user tabs away from the input field
2. the user clicks anywhere else on the page (outside the calendar/input)

![image](https://user-images.githubusercontent.com/1902973/96385273-10180e80-1150-11eb-8495-dc1ad542f1d1.png)

- The datepicker code is in [InputDatepicker.vue](https://github.com/sbine/bdgt/blob/master/resources/js/components/interface/InputDatepicker.vue)
- [`vue-clickaway`](https://github.com/sbine/bdgt/blob/master/resources/js/components/utilities/Toggle.vue#L2) is already included and might help with the 2nd requirement
- To work on this you'll need to know how to [build the frontend assets](https://github.com/sbine/bdgt/blob/master/README.md#building-the-frontend-assets)

**Comment by IsautierEloise** [comment]
Can I take this one ?

**Comment by sbine** [comment]
@IsautierEloise sure thing!
