### ISSUE TITLE
NotFoundHttpException on calculators/savings path

### ISSUE THREAD

**Issue by martin3zra** [sbine/bdgt#7]
When i try to get Saving calculator, the app throw a exception

**Comment by afolson** [comment]
Are you running the latest version of the code? There was a commit (https://github.com/sbine/bdgt/commit/6dfffb5a7596c6b411e4883ddc075ae9351051ca) that should prevent this from happening.

If you're using the latest version of the app, are you able to provide the trace that's shown? Thanks!

**Comment by martin3zra** [comment]
As I see this is the commit that owns the repository when you clone. 5b4296a

**Comment by afolson** [comment]
Do you also see that when you run `git log` as the latest commit?

Are you able to provide the trace for the error?

**Comment by martin3zra** [comment]
@afolson 
![screen shot 2016-07-29 at 3 48 58 pm](https://cloud.githubusercontent.com/assets/7558568/17261514/1c75a8ca-55a4-11e6-8042-49742f06fd5b.png)

**Comment by sbine** [comment]
Hey @martin3zra! If you pull the latest commits into your fork that should fix the NotFoundHttpException -- here's how you can do that:
`git remote add sbine git@github.com:sbine/bdgt.git`
`git fetch sbine`
`git merge sbine/master`
